all : 
	gcc -g -o test2 test2.c -pthread
	gcc -g -o test3 test3.c -pthread
	gcc -g -o test4 test4.c -pthread
	gcc -g -o test5 test5.c -pthread
	gcc -g -o test6 test6.c -pthread
	gcc -g -o pred1 pred1.c -pthread
	gcc -g -o pred2 pred2.c -pthread
	gcc -g -o pred3 pred3.c -pthread
	gcc -g -o pred4 pred4.c -pthread

clean :
	rm test2 test3 test4 test5 test6 pred1 pred2 pred3 pred4
