all : 
	gcc -g -o test2 test2.c -pthread
	gcc -g -o test3 test3.c -pthread
	gcc -g -o test4 test4.c -pthread
	gcc -g -o test5 test5.c -pthread
	gcc -g -o test6 test6.c -pthread

clean :
	rm test2 test3 test4 test5 test6
